language: generic
dist: trusty
addons:
  apt:
    packages:
      - emacs
script: make test
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/848b93e13f8e6ab0cc86
    on_success: always
    on_failure: always
    on_start: always
