language: generic
sudo: false
env:
  global:
    - CURL="curl -fsSkL --retry 9 --retry-delay 9"
  matrix:
  - EMACS_VERSION=24.3
  - EMACS_VERSION=24.4
  - EMACS_VERSION=24.5
  - EMACS_VERSION=25
  - EMACS_VERSION=26
  - EMACS_VERSION=master
dist: trusty
addons:
  apt:
    packages:
      - emacs
      - texinfo
script:
  - make
  - make test
  - make info
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/848b93e13f8e6ab0cc86
    on_success: always
    on_failure: always
    on_start: always
  email:
    on_success: change
    on_failure: always
    on_start: never
