sudo: false
language: generic
env:
  global:
    - CURL="curl -fsSkL --retry 9 --retry-delay 9"
    - GHRAW="https://raw.githubusercontent.com"
  matrix:
    - EMACS_VERSION=25.1
    # 25.2 is identical to 25.3 except for a critical security bug in
    # enriched text mode (see Emacs Bug#28350).
    - EMACS_VERSION=25.3
    - EMACS_VERSION=26.1
    - EMACS_VERSION=26     # 26.1.50, emacs-26 branch, built daily
    - EMACS_VERSION=master # 27.0.50, master branch, built daily
  allow_failures:
    - env: EMACS_VERSION=master
install:
  - $CURL -O https://github.com/npostavs/emacs-travis/releases/download/bins/emacs-bin-${EMACS_VERSION}.tar.gz
  - tar -xaf emacs-bin-${EMACS_VERSION}.tar.gz -C /
  - export EMACS=/tmp/emacs/bin/emacs
  - $CURL -O ${GHRAW}/magnars/dash.el/master/dash.el
  - $CURL -O ${GHRAW}/magit/ghub/master/ghub.el
  - $CURL -O ${GHRAW}/magit/ghub/master/ghub-graphql.el
  - $CURL -O ${GHRAW}/vermiculus/graphql.el/master/graphql.el
  - $CURL -O ${GHRAW}/magit/magit-popup/master/magit-popup.el
  - $CURL -O ${GHRAW}/volrath/treepy.el/master/treepy.el
  - $CURL -O ${GHRAW}/magit/with-editor/master/with-editor.el
  - $EMACS -Q --batch -L . -f batch-byte-compile dash.el ghub.el ghub-graphql.el graphql.el magit-popup.el treepy.el with-editor.el
  - $EMACS --version
script:
  - git config --global user.name "A U Thor"
  - git config --global user.email a.u.thor@example.com
  - git tag 0
  - make lisp EMACSBIN=$EMACS DASH_DIR=$PWD
  - make test EMACSBIN=$EMACS DASH_DIR=$PWD
notifications:
  email:
    # Default is change, but that includes a new branch's 1st success.
    on_success: never
    on_failure: always # The default.
