sudo: false
language: generic
env:
  global:
    - CURL="curl -fsSkL --retry 9 --retry-delay 9"
    - EMACS_BASE=https://github.com/npostavs/emacs-travis/releases/download/bins
    - GHRAW="https://raw.githubusercontent.com"
  matrix:
    - EMACS_VERSION=25.1
    - EMACS_VERSION=25.3
    - EMACS_VERSION=26.1
    - EMACS_VERSION=26
    - EMACS_VERSION=master
  allow_failures:
    - env: EMACS_VERSION=master
install:
  - $CURL -O ${GHRAW}/magnars/dash.el/master/dash.el
  - $CURL -O ${GHRAW}/vermiculus/graphql.el/master/graphql.el
  - $CURL -O ${GHRAW}/volrath/treepy.el/master/treepy.el
  - $CURL -O ${EMACS_BASE}/emacs-bin-${EMACS_VERSION}.tar.gz
  - tar -xaf emacs-bin-${EMACS_VERSION}.tar.gz -C /
  - export EMACS=/tmp/emacs/bin/emacs
  - $EMACS --version
script:
  - make lisp
notifications:
  email:
    on_success: never
    on_failure: always
